{"uuid": "341455f4-5eab-4132-8bba-11cc775ae198", "children": ["3829b24b-17bd-42a8-b0a7-3e6e0e91409b"], "befores": [{"name": "browser_manage", "status": "passed", "start": 1698318670924, "stop": 1698318670925}], "afters": [{"name": "browser_manage::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55f53df756c3 <unknown>\n#1 0x55f53dc4b1e7 <unknown>\n#2 0x55f53dc7e526 <unknown>\n#3 0x55f53dc7a69c <unknown>\n#4 0x55f53dcbd23a <unknown>\n#5 0x55f53dcb3e93 <unknown>\n#6 0x55f53dc86934 <unknown>\n#7 0x55f53dc8771e <unknown>\n#8 0x55f53df3acc8 <unknown>\n#9 0x55f53df3ec00 <unknown>\n#10 0x55f53df491ac <unknown>\n#11 0x55f53df3f818 <unknown>\n#12 0x55f53df0c28f <unknown>\n#13 0x55f53df63e98 <unknown>\n#14 0x55f53df64069 <unknown>\n#15 0x55f53df74853 <unknown>\n#16 0x7f90c1a94ac3 <unknown>\n\n", "trace": "  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/home/roman/PycharmProjects/selene_in_action/tests/conftest.py\", line 13, in browser_manage\n    browser.quit()\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selene/core/entity.py\", line 1205, in quit\n    self.driver.quit()\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selene/core/entity.py\", line 1100, in driver\n    return self.config.driver\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selene/core/configuration.py\", line 343, in __get__\n    driver = config.build_driver_strategy(config)\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selene/core/configuration.py\", line 171, in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selene/core/configuration.py\", line 93, in install_and_build_chrome\n    return Chrome(\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/home/roman/PycharmProjects/selene_in_action/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698318673270, "stop": 1698318674098}], "start": 1698318670924, "stop": 1698318674098}